### PR TITLE
Use Go 1.6 in Drone and golang-version-check.

### PR DESCRIPTION
**Pull request by peggyl**
You were assigned as the most active recent contributor to this repo.
Please reassign and share the joy of Go 1.6 if needed, or ask in #golang
if you have any questions.

### CODE REVIEW

**Comment by d-sparks** [comment]
Drone build failed.  Hitting rebuild, but we might want to make sure it was a true fluke before ships.

**Comment by d-sparks** [comment]
OK, it passed a bunch of times.  LGTM

**Comment by d-sparks** [comment]
Actually, @peggy can we chat briefly before ships?

**Comment by peggyl** [comment]
@d-sparks to test in clever-dev and merge/deploy.

**Comment by natebrennand** [comment]
bump @d-sparks 
Can this be merged or are you going to test in staging? FWIW, I would be astounded if we saw behavior changes

**Pull request merged**
